const allDipositions = [
  " ",
  "Debtor took info",
  "3rd party took info",
  "POE took info",
  "Left VM",
  "N/A, no VM",
  "VM full",
  "VM not set up",
  "Ringing only",
  "Dead air",
  "Busy tone",
  "Not accepting calls",
  "Restricted ",
  "Not callable",
  "Call can't be completed",
  "Not reachable",
  "Not available",
  "Unallocated # msg",
  "Incoming calls disabled",
  "No routes found",
  "Robo-Killer blocked",
  "DSL noise",
  "Wrong number",
  "'Wrong number', hung up",
  "Unrelated business",
  "Memory full msg",
  "Language Barrier",
  "Disconnected",
  "DO NOT CALL",
];

export default allDipositions;
