const allStatusCodes = [
  "--",
  "[1st Pass] 1st Pass",
  "[2nd Pass] 2nd Pass",
  "[3rd Pass] 3rd Pass",
  "[BK] BK",
  "ATTORNEY",
  "Broken Promise",
  "Broken Promise REDIAL",
  "CHARGEBACK",
  "CLAIMS BK",
  "CLOSED",
  "DECEASED",
  "DECLINED",
  "DIALER",
  "DIRECT DEBTOR",
  "DIRECT DEBTOR SPUSE",
  "DOUBLE SOLD",
  "DUPLICATES",
  "HIT BY OTAY",
  "HOT",
  "JAIL",
  "LEGAL PRC RECOMM",
  "NEEDS RESTAT",
  "NEEDS SKIP",
  "NEW IMPORT",
  "NO SKIPS HIT",
  "NSF",
  "OPEN",
  "OTR",
  "PIF",
  "POE FIRST PASS",
  "PPA",
  "PROMISE TO PAY",
  "RTP [ANGRY]",
  "RTP [DISPUTE]",
  "RTP [NO MONEY]",
  "SIF",
  "SKIPPED POE",
  "STAT 3RD PARTY",
  "STAT MOTHER/FATHER",
  "VERIFIED POE",
  "WRONG INFO, NEEDS RESKIP",
  "[LINKED/DUPLICATES] LINKED",
  "[LINKED/DUPLICATES] DUPLICATES",
  "NEW INFO",
  "PAID OFF PREV COMPANY",
];

export default allStatusCodes;
